Models/ErrorViewModel.cs
using System;

namespace RecipeBuilderFinalProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/RecipeContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecipeBuilderFinalProject.Models
{
    public class RecipeContext:DbContext
    {

        public RecipeContext(DbContextOptions<RecipeContext> options) : base(options)
        {

        }
        public DbSet<RecipeModel> RecipeModels { get; set; }

    }
}

Models/RecipeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RecipeBuilderFinalProject.Models
{
    public class RecipeModel
    {
        [Key]
        [Required(ErrorMessage = "This field is requaired")]
        public int Id { get; set; }


        [Column(TypeName = "nvarchar(250)")]
        [Required(ErrorMessage = "This field is requaired")]
        [DisplayName("Preap Time in minutes")]
        public double PrepTime { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [Required(ErrorMessage = "This field is requaired")]
        [DisplayName("Recipe Name")]
        public string RecipeName { get; set; }

        [Column(TypeName = "nvarchar(100)")]
        [Required(ErrorMessage = "This field is requaired")]
        [DisplayName("Recipe Destination")]
        public string RecipeDescription { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RecipeBuilderFinalProject.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RecipeBuilderFinalProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RecipeModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecipeBuilderFinalProject.Models;

namespace RecipeBuilderFinalProject.Controllers
{
    public class RecipeModelsController : Controller
    {
        public readonly RecipeContext _context;

        public RecipeModelsController(RecipeContext context)
        {
            _context = context;
        }

        // GET: RecipeModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.RecipeModels.ToListAsync());
        }

        // GET: RecipeModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipeModel = await _context.RecipeModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recipeModel == null)
            {
                return NotFound();
            }

            return View(recipeModel);
        }

        // GET: RecipeModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RecipeModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PrepTime,RecipeName,RecipeDescription")] RecipeModel recipeModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(recipeModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(recipeModel);
        }

        // GET: RecipeModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipeModel = await _context.RecipeModels.FindAsync(id);
            if (recipeModel == null)
            {
                return NotFound();
            }
            return View(recipeModel);
        }

        // POST: RecipeModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PrepTime,RecipeName,RecipeDescription")] RecipeModel recipeModel)
        {
            if (id != recipeModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recipeModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecipeModelExists(recipeModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(recipeModel);
        }

        // GET: RecipeModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipeModel = await _context.RecipeModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recipeModel == null)
            {
                return NotFound();
            }

            return View(recipeModel);
        }

        // POST: RecipeModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var recipeModel = await _context.RecipeModels.FindAsync(id);
            _context.RecipeModels.Remove(recipeModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecipeModelExists(int id)
        {
            return _context.RecipeModels.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/RecipeModels/Create.cshtml
@model RecipeBuilderFinalProject.Models.RecipeModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>RecipeModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PrepTime" class="control-label"></label>
                <input asp-for="PrepTime" class="form-control" />
                <span asp-validation-for="PrepTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipeName" class="control-label"></label>
                <input asp-for="RecipeName" class="form-control" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipeDescription" class="control-label"></label>
                <input asp-for="RecipeDescription" class="form-control" />
                <span asp-validation-for="RecipeDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/RecipeModels/Delete.cshtml
@model RecipeBuilderFinalProject.Models.RecipeModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RecipeModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrepTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrepTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecipeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecipeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecipeDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecipeDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/RecipeModels/Details.cshtml
@model RecipeBuilderFinalProject.Models.RecipeModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>RecipeModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrepTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrepTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecipeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecipeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecipeDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecipeDescription)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/RecipeModels/Edit.cshtml
@model RecipeBuilderFinalProject.Models.RecipeModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RecipeModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PrepTime" class="control-label"></label>
                <input asp-for="PrepTime" class="form-control" />
                <span asp-validation-for="PrepTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipeName" class="control-label"></label>
                <input asp-for="RecipeName" class="form-control" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipeDescription" class="control-label"></label>
                <input asp-for="RecipeDescription" class="form-control" />
                <span asp-validation-for="RecipeDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/RecipeModels/Index.cshtml
@model IEnumerable<RecipeBuilderFinalProject.Models.RecipeModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Recipe Builder</h1>

<h2>Yo, what up? You Hungry?</h2>
<h3>
    Then you're in the right place
</h3>
<h4>----------------</h4>
<p>
    <a asp-action="Create">Create Recipe!!</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PrepTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RecipeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RecipeDescription)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PrepTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecipeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecipeDescription)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecipeBuilderFinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel=" stylesheet"hert="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"/>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="RecipeModels" asp-action="Index">Recipe Builder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RecipeBuilderFinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>